name: Lint and build

on:
  push:
  workflow_dispatch:
    inputs:
      upload:
        type: choice
        options:
          - default
          - github_pages
          - none
        default: default
        description: 'Upload artifact type'
  workflow_call:
    inputs:
      upload_for_github_pages:
        type: boolean
        default: true
        description: 'Upload as GitHub pages artifact'

# Allow one concurrent run for each branch
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # Read-only permissions for GITHUB_TOKEN
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Upload artifact
        if: ${{ !inputs.upload_for_github_pages || inputs.upload == 'default' }}
        uses: actions/upload-artifact@v3
        with:
          name: 'build'
          path: 'dist/*'

      - name: Upload Pages artifact
        if: ${{ inputs.upload_for_github_pages || inputs.upload == 'github_pages' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'
